name: Laravel CI/CD Pipeline

# نوع النظام الأساسي
on:
  push:
    branches:
      - master  # أو أي branch تاني انت حابب تشتغل عليه
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # هنشغل الـ job ده على آخر نسخة من Ubuntu

    steps:
      # 1. عمل checkout للكود
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. تثبيت PHP و Composer
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # خلي بالك من النسخة دي، خليها متوافقة مع Laravel
          extensions: mbstring, xml, bcmath

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist

      # 3. تنفيذ الاختبارات
      - name: Run tests
        run: |
          php artisan test

      # 4. نشر التطبيق بعد النجاح (إذا كنت عايز تعمل deploy)
      - name: Deploy to production
        if: success()
        run: |
          echo "Deploying to production server..."
          # هنا تقدر تضيف أي خطوة لنقل الملفات على السيرفر
